const menu = [
  {
    id: 1,
    title: 'Localisation',
    category: 'Annexe',
    loc: 'Annexe',
    img: '/images/Annexe.jpg',
  },
  {
    id: 2,
    title: 'Extincteurs',
    category: 'Annexe',
    loc: 'Annexe',
    img: '/images/Annexe Extincteurs.jpg',
  },
  {
    id: 3,
    title: 'Détecteurs',
    category: 'Annexe',
    loc: 'Annexe',
    img: '/images/Annexe DAI.jpg',
  },
  {
    id: 4,
    title: 'Localisation',
    category: 'Evasan',
    loc: 'Evasan',
    img: '/images/Evasan.jpg',
  },
  {
    id: 5,
    title: 'Extincteurs',
    category: 'Evasan',
    loc: 'Evasan',
    img: '/images/Evasan Extincteurs.jpg',
  },
  {
    id: 6,
    title: 'Détecteurs',
    category: 'Evasan',
    loc: 'Evasan',
    img: '/images/Evasan Dai.jpg',
  },
  {
    id: 7,
    title: 'Localisation',
    category: 'R-1',
    loc: 'R-1',
    img: '/images/Bat-1.jpg',
  },
  {
    id: 8,
    title: 'Extincteurs',
    category: 'R-1',
    loc: 'R-1',
    img: '/images/Bat-1 extincteurs.jpg',
  },
  {
    id: 9,
    title: 'Détecteurs',
    category: 'R-1',
    loc: 'R-1',
    img: '/images/Bat-1 DAI.jpg',
  },
  {
    id: 10,
    title: 'Localisation',
    category: 'RDC',
    loc: 'RDC',
    img: '/images/Bat 0.jpg',
  },
  {
    id: 11,
    title: 'Extincteurs',
    category: 'RDC',
    loc: 'RDC',
    img: '/images/item-9.jpeg',
  },
  {
    id: 12,
    title: 'Détecteurs',
    category: 'RDC',
    loc: 'RDC',

    img: '/images/item-3.jpeg',
  },
  {
    id: 13,
    title: 'Localisation',
    category: 'R+1',
    loc: 'R+1',
    img: '/images/Bat 1.jpg',
  },
  {
    id: 14,
    title: 'Extincteurs',
    category: 'R+1',
    loc: 'R+1',
    img: '/images/item-2.jpeg',
  },
  {
    id: 15,
    title: 'Détecteurs',
    category: 'R+1',
    loc: 'R+1',
    img: '/images/item-9.jpeg',
  },
  {
    id: 16,
    title: 'Localisation',
    category: 'R+2',
    loc: 'R+2',
    img: '/images/Bat2.jpg',
  },
  {
    id: 17,
    title: 'Extincteurs',
    category: 'R+2',
    loc: 'R+2',
    img: '/images/item-8.jpeg',
  },
  {
    id: 18,
    title: 'Détecteurs',
    category: 'R+2',
    loc: 'R+2',
    img: '/images/item-1.jpeg',
  },
  {
    id: 19,
    title: 'Localisation',
    category: 'R+3',
    loc: 'R+3',
    img: '/images/Bat3.jpg',
  },
  {
    id: 20,
    title: 'Extincteurs',
    category: 'R+3',
    loc: 'R+3',
    img: '/images/item-8.jpeg',
  },
  {
    id: 21,
    title: 'Détecteurs',
    category: 'R+3',
    loc: 'R+3',
    img: '/images/Bat3 Dai.jpg',
  },
  {
    id: 22,
    title: 'Localisation',
    category: 'R+4',
    loc: 'R+4',
    img: '/images/Bat4.jpg',
  },
  {
    id: 23,
    title: 'Extincteurs',
    category: 'R+4',
    loc: 'R+4',
    img: '/images/Bat4 Extincteurs.jpg',
  },
  {
    id: 24,
    title: 'Détecteurs',
    category: 'R+4',
    loc: 'R+4',
    img: '/images/Bat4 Dai.jpg',
  },
];
export default menu;
